id: P94CFA06D
initial_creation_type: input
source_metadata:
  title: Dudjom Rinpoche Series
  language: zh
  description: 'We present the following texts by Kyabje Dudjom Rinpoche Jikdral Yeshe
    Dorje (bdud ''joms ''jigs bral ye shes rdo rje, 1904–1987), the renowned yogi
    and scholar and first appointed head of the Nyingma school in exile:'
  volume:
    f6e03c81546f42d58b9e53961de0be3e:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Advice
    ebda1eef7dc74bc3b94fc23fb7f92fe5:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Benefits
    31cf3ad227394472a6c2b452083e67b0:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    ba9a5794870640f0beb162e542060a77:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    a2427d903c724c0fa93bb1a0963cc0af:
      title: Concise Consecration
      parent: Consecration
    6a0e20953032458faaae0a33945458cc:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Dharma Protectors
    649de65ee12b401b85977de34e4ca4bf:
      title: Dzogchen Aspiration Prayer
      parent: Dzogchen
    adb7f45a97ff4230b2ec5f930b4886c5:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Dzogchen
    f0d0f41ea4e94f56857e43febbcd2454:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Dzogchen
    86ec21c919114f5da01a1af2c65a4426:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Guru Rinpoche Prayers
    99b5f7ce87ca42f8ac580b2fd53eefe7:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Guru Rinpoche Prayers
    043bb098c2794232b2a8cbad393e480a:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Guru Rinpoche Prayers
    725bd3801b00488a912befc8aef302c7:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Guru Rinpoche Prayers
    39be60b3ddab4cebb9b3ecb40c77b978:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Guru Rinpoche Prayers
    7540d28d7b3441028d3818be5d03e87e:
      title: A Concise Lineage Prayer
      parent: Lineage Prayers
    9a6235bbd8804554a97df58caf62e93e:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    468c376f87e34470bbe658adddf5c038:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    d21b348404c64e26924e8cbb706572f6:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    59e0517974514d0ca17b20d1db9577ba:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    d2f7dd652c95426e9772422a468ed59b:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Long Life Prayers
    5aefcd40f3ab403fb4c96f1239b0dfa0:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Ngöndro
    3da32f8697db4a178194a6e06997b0a2:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Ngöndro
    335e9b44671841e08c1fe34a89070b2c:
      title: Brief Red Sur Offering
      parent: Offering
    56beea6ca89f4b8fb45f6bd4a1d89a6d:
      title: Brief Sur Offering
      parent: Offering
    acda6f174d984af4ace2bb0ca7baca13:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayers
    324a6b75304d4c0bada0c2e217e28f21:
      title: Essence and Embodiment of All the Buddhas
      parent: Prayers
    389dfdb8dc274a6e8416bc85aba83ca1:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    0210b762825845b888fdecffb0c0127f:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Sādhanas
    16710298ef1f43e08e19f72d7f84a18a:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    7aac607a2ff64888846c27c69e961b8c:
      title: A Daily Practice of Lama Sangdü
      parent: Sādhanas
    18d31ff90ff6495c823ec0defa2efb98:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    337fa6c5d96f4207be0bef0ee57e08f3:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    7976a09916514b6a909568754bee194b:
      title: Daily Practice of Dorje Gotrab
      parent: Sādhanas
    642de9dac96a4952840d81932203aca1:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sādhanas
    c79c76ce0a964dcda15a8d77c0c3734a:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
    1d671cce1e234f9991fb01d7cee41c32:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    4852b96ba311455ebbd04b691a94f380:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    d7c28cdd0b9d4f6b98d463a8244b4d9f:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    3b37ee771d6f43719ce0019f79499420:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
    d9b82b2bd4b040e0b013bfdc6f8b91c9:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
    c0d77a45ef4a463287e94aaeb99f7162:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      parent: Sojong
    1a892dcab0e4488ca77f7b3a5b67e556:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Tsok
    90c2e976d6bb4e469ea10758779742a3:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Tsok
    07bd7d98f6de4e1d9178ab47b4a9f063:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-02-28T23:10:30.056893'
last_modified_at: '2022-02-28T23:10:30.056895'
